# Generated by Django 5.1.3 on 2024-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='idade',
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(null=True),
        ),
    ]
